---
apiVersion: apps/v1
kind: Deployment

metadata: 
  name: nwapp-deploy
  namespace: nwns
  labels:
    name: nwapp
    version: v1

spec:
  replicas: 3
  selector:
    matchLabels:
      name: nwapp
      version: v1
  template: 
    metadata:
      name: nwapp-pod
      labels: 
        name: nwapp
        version: v1
    spec:
      containers:
      - name: nwapp-container
        image: stackupiss/northwind-app:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: nwapp-config
              key: db_host
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nwapp-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nwapp-secret
              key: db_password
        ports:
        - name: nwapp-port
          containerPort: 3000

---
apiVersion: v1
kind: Service

metadata: 
  name: nwapp-svc
  namespace: nwns
  labels:
    name: nwapp-svc
    version: v1

spec:
  type: LoadBalancer
  selector: 
    name: nwapp
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: nwapp-port