---
apiVersion: v1
kind: Namespace

metadata:
  name: nwns
  labels:
    version: v1

---
apiVersion: v1
kind: Secret

metadata:
  name: nwapp-secret
  namespace: nwns

data:
  db_user: cm9vdA==
  db_password: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nwapp-config
  namespace: nwns

data:
  db_host: nwdb-svc.nwns.svc.cluster.local


